### ISSUE TITLE
Latest main fails with previosly working keymap

### ISSUE THREAD

**Issue by magicDGS** [caksoylar/keymap-drawer#130]
Using the main version of the tool locally and on github to try out the solution for #116, I get the following error on the parse step for my keymap that was working before the treesitter refactoring:

```bash
2024-11-19T16:34:53.3708818Z INFO: using config args: -c draw-config/config.yaml
2024-11-19T16:34:53.3723324Z INFO: drawing for glove80
2024-11-19T16:34:53.3729772Z INFO:   got extra parse args: 
2024-11-19T16:34:53.3733302Z INFO:   got extra draw args: 
2024-11-19T16:34:53.7109801Z Traceback (most recent call last):
2024-11-19T16:34:53.7111152Z   File "/opt/pipx_bin/keymap", line 8, in <module>
2024-11-19T16:34:53.7112077Z     sys.exit(main())
2024-11-19T16:34:53.7113987Z   File "/opt/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 236, in main
2024-11-19T16:34:53.7115452Z     parse(args, config)
2024-11-19T16:34:53.7116954Z   File "/opt/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/__main__.py", line 83, in parse
2024-11-19T16:34:53.7118089Z     ).parse(args.zmk_keymap)
2024-11-19T16:34:53.7118898Z   File "/opt/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse/parse.py", line 167, in parse
2024-11-19T16:34:53.7119878Z     layout, keymap_data = self._parse(in_buf.read(), in_buf.name)
2024-11-19T16:34:53.7120842Z   File "/opt/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse/zmk.py", line 268, in _parse
2024-11-19T16:34:53.7121596Z     layers = self._get_layers(dts)
2024-11-19T16:34:53.7122546Z   File "/opt/pipx/venvs/keymap-drawer/lib/python3.10/site-packages/keymap_drawer/parse/zmk.py", line 166, in _get_layers
2024-11-19T16:34:53.7123877Z     raise ParseError('Could not find any keymap nodes with "zmk,keymap" compatible property')
2024-11-19T16:34:53.7124842Z keymap_drawer.parse.parse.ParseError: Could not find any keymap nodes with "zmk,keymap" compatible property
```
(extract from https://github.com/magicDGS/glove80-keymap-config/actions/runs/11917519204).

**Comment by magicDGS** [comment]
Hintd: using the previous commit before introducing the tree-sitter implementation works: https://github.com/magicDGS/glove80-keymap-config/actions/runs/11917649047 - this means that indeed the main problem is with tree-sitter parsing.

**Comment by caksoylar** [comment]
Thanks, I'll add your keymap to your test cases and figure out why it's not working.

**Comment by caksoylar** [comment]
I believe a31b4487c510a9ee347bc31bc3e574fde54b10c6 should fix it, can you test also? The undefined preprocessor macros like `ZMK_MACRO` that come from ZMK threw off tree-sitter, so some of the root nodes weren't detected.

**Comment by magicDGS** [comment]
Looks like it is still failing: https://github.com/magicDGS/glove80-keymap-config/actions/runs/11921610231/job/33226104809

Now it doesn't find the `zmk_defines.h` newly added definition.

---

_Off-topic as it came to my mind when looking at the header file: would this work with modules such ZMK_HELPERS, as I am planning to eventually include it on my keyboard config?_

**Comment by caksoylar** [comment]
Yeah, I messed up and forgot to add the new file to the manifest. Just pushed a fix, please try again.

> Off-topic as it came to my mind when looking at the header file: would this work with modules such ZMK_HELPERS, as I am planning to eventually include it on my keyboard config?

Yes, though you have to configure a bit to get it to read the extra headers: https://github.com/urob/zmk-helpers/blob/main/docs/keymap_drawer.md

**Comment by magicDGS** [comment]
Parsing now works (looks like), but the timeout is happening. So I will close this issue as fixed.

---

For the off-topic question, I was referring if it will work with the overriden ZMK_MACRO from the helpers (and also, as we are here, with the ZMK_LAYAOUT that I have tried with the released version and it was not detecting any layer....)
